spring.application.name=bdss-system

spring.datasource.url=${BDSS_DB_URL:jdbc:h2:mem:bdss-dev;MODE=MSSQLServer;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1}
spring.datasource.username=${BDSS_DB_USERNAME:sa}
spring.datasource.password=${BDSS_DB_PASSWORD:}
spring.datasource.driver-class-name=${BDSS_DB_DRIVER:org.h2.Driver}

spring.jpa.properties.hibernate.dialect=${BDSS_JPA_DIALECT:org.hibernate.dialect.H2Dialect}
spring.jpa.hibernate.ddl-auto=${BDSS_JPA_DDL_AUTO:create}

spring.main.allow-circular-references=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.mail.host=${BDSS_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${BDSS_MAIL_PORT:587}
spring.mail.username=${BDSS_MAIL_USERNAME:demofortest999@gmail.com}
spring.mail.password=${BDSS_MAIL_PASSWORD:jieqwxkwsmdrrjok}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
